### PR TITLE
Closes #84: Fix (rewrite) CIF importer

### LINKED ISSUE #84: Fix CIF metadata importer

### PR DESCRIPTION
**Pull request by wtr-icm**

### CODE REVIEW

File: src/main/java/pl/edu/icm/pl/mxrdr/extension/importer/common/BaseDataContainer.java [hunk 1]
```diff
@@ -0,0 +1,81 @@
...
+        List<String> values = container.putIfAbsent(key, new ArrayList<>());
+        values = values != null ? values : container.get(key);
+        values.add(value != null ? value : EMPTY);
+        return (C) this;
+    }
+
+    /**
+     * Adds the value to the container.
+     */
+    protected C add(MxrdrMetadataField key, Optional<String> value) {
```
Comment (MrK191) [inline src/main/java/pl/edu/icm/pl/mxrdr/extension/importer/common/BaseDataContainer.java:60]: I think we should just accept nullable values and use optional in add(...) method.

**Review by MrK191 — CHANGES_REQUESTED** [review]

File: src/main/java/pl/edu/icm/pl/mxrdr/extension/importer/common/BaseDataContainer.java (hunk 1 above)
Comment (wtr-icm) [reply src/main/java/pl/edu/icm/pl/mxrdr/extension/importer/common/BaseDataContainer.java:60]: This change has two downsides:
1. It will force extracting value from `Optional` in nearly 20 places, which will add unnecessary noise in code.
2. It will move the logic of changing non-existing values to empty value from one well-defined place to (possibly) many locations without ensuring uniform behavior.

So I think it's better to leave it as is.
